export default {
  index: 'Introduction',
  '-- hardware': { type: 'separator', title: 'Hardware' },
  platform: 'Current chair: RAMMP Gen 1.5',
  'previous-generations': 'Previous generations',
  'gen-2-0': 'RAMMP Gen 2.0 (in development)',
  '-- software': { type: 'separator', title: 'Software stack' },
  software: 'Software versions & core repos',
  modules: 'Modules registry',
  '-- developing': { type: 'separator', title: 'Developing' },
  setup: 'Developer setup',
  development: 'Development flow',
  'git-workflow': 'Recommended git workflow',
  publishing: 'Publishing a module',
  interfaces: 'Interfaces',
  sheppy: 'sheppy',
  '-- subsystems': { type: 'separator', title: 'Subsystems' },
  'kinova-gen3-ros2': 'Controlling the arm',
  'rammp-teleop': 'Teleoperating the arm',
  'controlling-the-base': 'Controlling the base',
  'oak-d-pro-poe': 'OAK-D Pro PoE camera',
  contributing: { display: 'hidden' }
}
